const DEFAULT_KEY="admin123";
let products=JSON.parse(localStorage.getItem("electroisla_products")||"null")||[];
const save=()=>localStorage.setItem("electroisla_products",JSON.stringify(products));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function login(){if(document.getElementById("adminPass").value!==DEFAULT_KEY){alert("Clave incorrecta.");return}localStorage.setItem("electroisla_admin","1");show()}
function show(){document.getElementById("loginBox").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");render()}
function render(){const box=document.getElementById("adminProducts");box.innerHTML=products.length?products.map(p=>`<div class="admin-product ${p.available?"":"disabled"}"><div>${p.image?`<img src="${esc(p.image)}">`:"📦"}</div><div><h4>${esc(p.name)}</h4><small>${esc(p.category)} · $${Number(p.price).toFixed(2)} · ${esc(p.unit||"")} · ${p.available?"Disponible":"Oculto"}</small></div><div class="admin-actions"><button onclick="edit('${p.id}')">✏️</button><button onclick="toggle('${p.id}')">👁️</button><button onclick="removeP('${p.id}')">🗑️</button></div></div>`).join(""):"<p>No hay productos. Agrega el primero.</p>"}
function edit(id){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById("editId").value=p.id;document.getElementById("pName").value=p.name;document.getElementById("pCategory").value=p.category;document.getElementById("pPrice").value=p.price;document.getElementById("pUnit").value=p.unit||"";document.getElementById("pImage").value=p.image||"";document.getElementById("pDescription").value=p.description||"";document.getElementById("pAvailable").checked=p.available!==false;document.getElementById("formTitle").textContent="✏️ Editar producto";scrollTo(0,0)}
function toggle(id){const p=products.find(x=>x.id===id);if(p){p.available=!p.available;save();render()}}
function removeP(id){if(confirm("¿Eliminar este producto?")){products=products.filter(x=>x.id!==id);save();render()}}
document.getElementById("productForm").addEventListener("submit",e=>{e.preventDefault();const id=document.getElementById("editId").value;const p={id:id||Date.now().toString(),name:document.getElementById("pName").value.trim(),category:document.getElementById("pCategory").value,price:Number(document.getElementById("pPrice").value),unit:document.getElementById("pUnit").value.trim(),image:document.getElementById("pImage").value.trim(),description:document.getElementById("pDescription").value.trim(),available:document.getElementById("pAvailable").checked};if(id)products=products.map(x=>x.id===id?p:x);else products.push(p);save();reset();render()});
function reset(){document.getElementById("productForm").reset();document.getElementById("editId").value="";document.getElementById("formTitle").textContent="➕ Agregar producto";document.getElementById("pAvailable").checked=true}
document.getElementById("cancelEdit").onclick=reset;
document.getElementById("loginBtn").onclick=login;document.getElementById("logoutBtn").onclick=()=>{localStorage.removeItem("electroisla_admin");location.reload()};
if(localStorage.getItem("electroisla_admin")==="1")show();
